#pragma once

#define PIN_POT1_MOISTURE_SENSOR PIN_A0
#define PIN_POT2_MOISTURE_SENSOR PIN_A1
#define PIN_POT3_MOISTURE_SENSOR PIN_A2

#define PIN_ONEWIRE 				2
#define PIN_PUMP 					3
#define PIN_POT1_VALVE 				4
#define PIN_POT1_MOISTURE_VOLTAGE 	5
#define PIN_POT2_VALVE				6
#define PIN_POT2_MOISTURE_VOLTAGE 	7
#define PIN_POT3_VALVE				8
#define PIN_POT3_MOISTURE_VOLTAGE 	9

#define MOISTURE_READ_COUNT 10
#define MOISTURE_VOLTAGE_DELAY_MILLIS 10000
#define DRY_TIMER_HOURS 24
#define VALVE_DELAY_MILLIS 500
#define COOL_DOWN_SECONDS 21600 // 6h
#define MAX_WATERLESS_DAYS 5
#define WATER_SECONDS 10
#define BOOT_WATER_SECONDS 3
#define PAUSE_SECONDS 1200
#define PUMP_TURN_OFF_DELAY_MILLIS 500
#define TEMPERATURE_RESOLUTION 9
#define LOG_FILE "waterbot-%d.log"

#define LOGGER_SD 1
#define LOGGER_SERIAL 2
#define LOGGER LOGGER_SD

void pause(unsigned long seconds);
